version: '3.8'

services:
  grafana:
    image: grafana/grafana:11.1.2-ubuntu
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    restart: always
    user: "1000:1000"

volumes:
  grafana-storage:

networks:
  monitoring-network:
    external: true