global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka_exporter'
    static_configs:
      - targets: ['172.31.5.148:9308']
