version: '3.8'

networks:
  spark-net:
    driver: bridge

services:
  spark-master:
    image: bitnami/spark:3.5.1
    container_name: spark-master
    ports:
      - "8083:8083"  # Web UI port
      - "7077:7077"  # Master port
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8083
      - SPARK_MASTER_OPTS="-Dspark.port.maxRetries=100"
    networks:
      - spark-net